language: php

php:
  - 5.4
  - 5.5

matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
  - composer install --dev

script: phpunit --coverage-text

notifications:
  email:
    - r.janot+travis-ci@gmail.com
